version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run: |
        docker build --build-arg DOCKER_CERT_PATH -t test .
        docker run -v /var/run/docker.sock:/var/run/docker.sock -it --rm test
