version: 2

jobs:
  build:
    docker:
    - image: circleci/buildpack-deps:19.04
    steps:
    - setup_remote_docker
    - checkout
    - run: |
        docker build -t test .
        docker run -e DOCKER_HOST=$DOCKER_HOST -it --rm test

