version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run:
        name: Install current Go
        command: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install golang-go
    - run:
        name: Run tests
        command: |
          go test -v
